###
POST https://is-starknet-dev.gcba.gob.ar/create
Content-Type: application/json

{"type":"create","suffixData":{"deltaHash":"EiDEz7I5bN5tqN8Sjr9z6PcI0lbo6afk4H9_GPSBg7VKHQ","recoveryCommitment":["EiDknd_F2UGaC__Pie0tkCk3F8cMcxEazRj3sGq7-GE1fQ"]},"delta":{"updateCommitment":["EiDknd_F2UGaC__Pie0tkCk3F8cMcxEazRj3sGq7-GE1fQ"],"patches":[{"action":"replace","document":{"publicKeys":[{"id":"bbs2020","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"tBEOEN_Cq4Z-T1A3_xZHsBEZGu4kSdQ4Rn1NHE_BhEgDb_II-krYNc27QYl1sRfB","y":"EE8_bcWZJbxfWTN-En9mr38owA8afl2wyH4sdlW7m7pc7pN_pgq_ItiZEJRlmIJb"},"type":"Bls12381G1Key2020","purposes":["assertionMethod"]}],"services":[]}}]}}
###

GET http://modena.gcba-extrimian.com:8080/resolve/EiACA_9zYL1GALifoDfTS7zjDQ0EsfF8x7rrmb7xdB_Qwg HTTP/1.1

###

GET http://20.237.2.83/resolve/EiAdmFGd1gWLh0YzPGwvE8Ial1QC0nMTG0KEfV8NkkCQ1w HTTP/1.1

###

GET http://20.237.2.83/resolve/EiBJrYsmcJK48HZmHCu8z6huHADe6I2E5y0eLdkb2-MJ_w HTTP/1.1

###

GET http://localhost:3000/resolve/EiAclXc3n77TtJw4aOOXq6c0skuDP0c3sSMZ_yetaRpplA HTTP/1.1

###

GET https://credentials.extrimian.com/credentials/revoke/%7Bcredentia

###

POST https://credentials.extrimian.com/credentials/revoke/33456880
Content-Type: application/json

{
    "currentStatus": "Revoked",
    "statusReason": "Esta la revoco por prueba"
}


###

POST https://credentials.extrimian.com/credentials/verify/33456877 HTTP/1.1
